# Generated by Django 5.1 on 2024-08-28 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
        ('ws_connector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user_manager.user'),
            preserve_default=False,
        ),
    ]
