# Generated by Django 5.1.4 on 2024-12-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_connector', '0002_position_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='account_id',
            field=models.CharField(default='tfsa-12345', max_length=255),
            preserve_default=False,
        ),
    ]
