# Generated by Django 5.1.4 on 2025-01-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_connector', '0004_alter_position_user_credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='ws_access_token_expiry',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='ws_refresh_token',
        ),
    ]
