# Generated by Django 5.1.4 on 2024-12-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
        ('ws_connector', '0004_alter_position_user_credential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
